### ISSUE TITLE
legal wells don't print well when overflow

### ISSUE THREAD

**Issue by deargle** [NYUCCL/psiTurk#235]
The 'print a copy of this` buttons in the example files currently print the window, which might involve printing only part of the consent or debrief statements if they're so long that they scroll. this functionality can be improved thusly:

```css
<style>
@media print {
    body * {
        visibility: hidden;
    }
    .legal, .legal * {
        visibility: visible;
    }
    .legal {
        position: absolute;
        left: 0;
        top: 0;
        overflow:visible;
    }
}
</style>
```
It'll only print the legal well, and it'll expand it. Code lifted from [SO](http://stackoverflow.com/questions/468881/print-div-id-printarea-div-only/2618980#2618980). I'll integrate this into the example files soon.
